import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { i18nConfig } from '../../i18nConfig'
import { DefaultViewportMetadata } from '../utils/Metadata/viewportMetadata'

const inter = Inter({ subsets: ['latin'] })

export const viewport = DefaultViewportMetadata;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: "https://nextjs.org/favicon.ico"
  },
  
}

export async function generateStaticParams() {
  return i18nConfig.locales.map((locale: string) => ({locale}))
}

export default function RootLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode,
  params: {locale: string}
}) {
  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
