import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { i18nConfig } from '../../i18nConfig'

const inter = Inter({ subsets: ['latin'] })

export const revalidate = 60;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AppLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode,
  params: {locale: string}
}) {
  return (
    <main>{children}</main>
  )
}
